# Generated by Django 4.2.5 on 2023-10-02 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beatbooker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
